# ABP2-I419 Phase 3 (Sahil 2026-06-17, Out of BRD) — Stock Entry
# Manufacture customizations. Implements the FRD's Process Logic L08..L12
# (process auto-fetch, target defaults, expense/PO rate fetch) and the
# server side of Validations VAL-08..14.
#
# Wired in hooks.py:
#   Stock Entry:
#     validate -> validate_stock_entry_manufacture
# (the CC/Project guard from Phase 2 stays wired separately).

from __future__ import annotations

import frappe
from frappe import _
from frappe.utils import flt

# ABP2-I466 (Raj Tiwari 2026-06-18) — _stock_entry_is_in_scope lives in
# the sibling cc_project_guard module. Without this import the symbol
# was undefined at validate-time inside inherit_se_from_production_plan,
# and EVERY Stock Entry save threw `NameError: name
# '_stock_entry_is_in_scope' is not defined` (even Material Receipt
# rows that have nothing to do with Production Plan logic).
from detox_project.detox_project.overrides.cc_project_guard import (
    _stock_entry_is_in_scope,
)


# Stock Entry types covered by Phase 3 logic.
MFG_TYPES = {
    "Manufacture",
    "Material Transfer for Manufacture",
    "Repack",
}


# --------------------------------------------------------------------------
# Whitelisted helper for the Client Script's auto-fetch.
# --------------------------------------------------------------------------
@frappe.whitelist()
def get_operation_rm_rows(production_plan: str, operation: str) -> list[dict]:
    """L08 — return RM/Service rows on the plan for the given operation.

    Used by the SE Manufacture Client Script: when the user picks a
    Process on the SE header, the client clears `items` then calls this
    method to repopulate with the operation's source rows (item, UOM,
    rate, qty_per_unit) — qty starts blank for the user to enter.
    """
    if not production_plan or not operation:
        return []
    rows = frappe.db.sql(
        """SELECT op.item_code, op.item_type, op.standard_uom, op.manual_uom,
                  op.standard_rate, op.qty_per_unit, op.multiply_by,
                  op.cost_center, op.project
           FROM `tabDetox Production Plan Operation` op
           WHERE op.parent = %s
             AND op.parenttype = 'Production Plan'
             AND op.operation_name = %s
           ORDER BY op.idx""",
        (production_plan, operation), as_dict=True,
    )
    enriched = []
    for r in rows:
        uom = r.manual_uom or r.standard_uom
        # Default expense account from Item master (L11).
        expense_account = _default_expense_account(r.item_code)
        # Item name for display.
        item_name = frappe.db.get_value("Item", r.item_code, "item_name") or r.item_code
        enriched.append({
            "item_code": r.item_code,
            "item_name": item_name,
            "item_type": r.item_type,
            "uom": uom,
            "stock_uom": r.standard_uom,
            "basic_rate": flt(r.standard_rate),
            "qty_per_unit": flt(r.qty_per_unit),
            "multiply_by": flt(r.multiply_by),
            "expense_account": expense_account,
            "cost_center": r.cost_center,
            "project": r.project,
        })
    return enriched


def _default_expense_account(item_code: str) -> str | None:
    """Pull the default expense account from Item master (L11)."""
    if not item_code:
        return None
    row = frappe.db.sql(
        """SELECT expense_account FROM `tabItem Default`
           WHERE parent = %s
             AND parenttype = 'Item'
             AND IFNULL(expense_account, '') != ''
           LIMIT 1""",
        item_code,
    )
    return row[0][0] if row else None


@frappe.whitelist()
def po_item_link_query(
    doctype: str | None = None,
    txt: str | None = None,
    searchfield: str | None = None,
    start: int = 0,
    page_len: int = 20,
    filters: dict | None = None,
) -> list[tuple]:
    """Sahil Image #34 — custom search for the PO Item picker on the
    Stock Entry items grid. Frappe's default Link picker shows the row's
    autogenerated hash `name`, which is meaningless. This query returns
    (hash, item_code, item_name, qty, rate) tuples so the autocomplete
    rows show 'item_code · item_name · qty · rate' instead of the hash.
    """
    filters = filters or {}
    parent = filters.get("parent")
    params: dict = {"start": int(start), "page_len": int(page_len)}
    where = ["parenttype = 'Purchase Order'"]
    if parent:
        where.append("parent = %(parent)s")
        params["parent"] = parent
    if txt:
        where.append("(item_code LIKE %(txt)s OR item_name LIKE %(txt)s)")
        params["txt"] = f"%{txt}%"
    return frappe.db.sql(
        f"""SELECT name, item_code, item_name, qty, rate
            FROM `tabPurchase Order Item`
            WHERE {' AND '.join(where)}
            ORDER BY idx
            LIMIT %(start)s, %(page_len)s""",
        params,
    )


@frappe.whitelist()
def get_plan_processes(production_plan: str) -> list[dict]:
    """Sahil Image #30 — the Process dropdown on the SE was empty
    because client-side frappe.db.get_list on the child DocType
    'Detox Production Plan Process' hit permission walls (the user
    has no direct read permission on the child; child perms inherit
    from parent only when accessed via the parent's bag). A
    server-side whitelisted SQL bypasses the issue and returns the
    plan's declared Operations + their Workstation."""
    if not production_plan:
        return []
    return frappe.db.sql(
        """SELECT operation_name, workstation, operation_seq
           FROM `tabDetox Production Plan Process`
           WHERE parent = %s AND parenttype = 'Production Plan'
           ORDER BY operation_seq, idx""",
        production_plan, as_dict=True,
    )


@frappe.whitelist()
def get_fg_defaults(production_plan: str, item_code: str) -> dict:
    """L10 — when a target FG row's item_code is set, return the
    matching Table 1 row's fg_warehouse + standard_costing_rate so the
    Client Script can stamp t_warehouse + basic_rate."""
    if not production_plan or not item_code:
        return {}
    row = frappe.db.sql(
        """SELECT fg_warehouse, standard_costing_rate
           FROM `tabDetox Production Plan FG`
           WHERE parent = %s
             AND parenttype = 'Production Plan'
             AND item_code = %s
           LIMIT 1""",
        (production_plan, item_code), as_dict=True,
    )
    if not row:
        return {}
    return {
        "t_warehouse": row[0].fg_warehouse,
        "basic_rate": flt(row[0].standard_costing_rate),
    }


# --------------------------------------------------------------------------
# Inherit dimensions from the linked Production Plan
# --------------------------------------------------------------------------
def inherit_se_from_production_plan(doc, method=None):
    """Sahil 2026-06-17 — when the SE is linked to a Production Plan,
    pull CC + Project off the plan onto the SE header AND propagate to
    every item row that's missing a cost_center. This stops ERPNext's
    get_default_cost_center from ever needing to fall back to
    Company.default_cost_center (the source of the 'Please set default
    Default Cost Center in Company …' throw).

    Fires on validate so it runs BEFORE ERPNext's standard validation.

    SE refactor (Sahil 2026-06-26): Stock Entry now uses the standard
    `cost_center` field (ERPNext 16.25+). The old proxy/`custom_cost_center`
    plumbing is gone. Production Plan still uses its own
    `custom_cost_center` Custom Field.
    """
    if not _stock_entry_is_in_scope(doc):
        return

    plan_name = doc.get("production_plan")
    if not plan_name or not frappe.db.exists("Production Plan", plan_name):
        return
    plan = frappe.db.get_value(
        "Production Plan", plan_name,
        ["custom_cost_center", "project"],
        as_dict=True,
    ) or {}
    cc = plan.get("custom_cost_center")
    pj = plan.get("project")
    if cc and not doc.get("cost_center"):
        doc.cost_center = cc
    if pj and not doc.get("project"):
        doc.project = pj
    # Propagate to every item row — blank rows inherit, populated rows
    # are left alone.
    final_cc = doc.get("cost_center") or cc
    final_pj = doc.get("project") or pj
    for row in (doc.get("items") or []):
        if final_cc and not row.get("cost_center"):
            row.cost_center = final_cc
        if final_pj and not row.get("project"):
            row.project = final_pj


# --------------------------------------------------------------------------
# Validate hook
# --------------------------------------------------------------------------
def validate_stock_entry_manufacture(doc, method=None):
    """Phase 3 validations (VAL-08, VAL-10, VAL-11, VAL-12, VAL-13).

    All fire ONLY on Manufacturing-flow SEs. CC + Project enforcement
    stays in cc_project_guard.validate_stock_entry.
    """
    purpose = (doc.get("stock_entry_type") or "").strip()
    if purpose not in MFG_TYPES:
        return

    # VAL-08 — process_selection mandatory before save / submit.
    if doc.get("production_plan") and not doc.get("custom_process_selection"):
        frappe.throw(
            _("Select a Process before adding production rows."),
            title=_("Process Selection missing"),
        )

    # VAL-11 — production_time bounds.
    pt = flt(doc.get("custom_production_time"))
    if pt:
        uom = (doc.get("custom_time_uom") or "Hours").strip()
        cap = 24.0 if uom == "Hours" else 24 * 60.0
        if pt <= 0 or pt >= cap:
            frappe.throw(
                _("Production Time must be greater than 0 and within a "
                  "single day for the selected unit ({0}).").format(uom),
                title=_("Production Time out of range"),
            )

    # VAL-12 — at least one finished/semi-finished target row with qty > 0
    # on a Manufacture entry.
    if purpose == "Manufacture":
        has_fg = any(
            row.get("is_finished_item") and flt(row.get("qty")) > 0
            for row in (doc.get("items") or [])
        )
        if not has_fg:
            frappe.throw(
                _("Enter at least one finished good with quantity to record "
                  "production."),
                title=_("Finished Good missing"),
            )

    # VAL-10 — source rows on a plan-driven SE should carry a PO link so
    # the variance report can price them. Only checked when the SE is
    # plan-driven; standalone Repack / Material Transfer / Manufacture
    # have no PO context to vary against.
    # ABP2-I466 reopen (Sahil 2026-06-25, MAT-STE-00502): a standalone
    # Repack with no Production Plan was being blocked on submit by
    # this check. The variance only matters when there IS a plan whose
    # source rows came from POs.
    # No-BOM plan reopen (2026-08-07): plan-driven SEs may legitimately
    # have source rows with no PO at all, so the hard throw is now a
    # soft warning — submit is never blocked. Rows that do carry a PO
    # keep the full variance flow; unlinked rows simply price at 0 in
    # Production Cost Comparison (which already guards for that).
    if doc.get("production_plan"):
        is_submit_path = (
            doc.docstatus == 1
            or getattr(doc, "_action", None) == "submit"
            or getattr(doc.flags, "validate_before_submit", False)
        )
        if is_submit_path:
            missing_rows = [
                idx
                for idx, row in enumerate(doc.get("items") or [], start=1)
                # Source rows have s_warehouse set.
                if row.get("s_warehouse")
                and (not row.get("custom_purchase_order")
                     or not row.get("custom_purchase_order_item"))
            ]
            if missing_rows:
                frappe.msgprint(
                    _("Row(s) {0}: no Purchase Order linked on the source "
                      "row — PO variance will not be calculated for these "
                      "rows.").format(
                        ", ".join("#{0}".format(i) for i in missing_rows)),
                    title=_("Purchase Order not linked"),
                    indicator="orange",
                )

    # VAL-13 — over-production warning (cumulative produced > planned).
    # Read total_produced from the matching Table 1 row; soft warning only.
    if purpose == "Manufacture" and doc.get("production_plan"):
        _warn_on_over_production(doc)


def _warn_on_over_production(doc) -> None:
    plan = doc.get("production_plan")
    if not plan:
        return
    # Per FG row in the SE, look up Table 1 planned qty + total_produced.
    for row in (doc.get("items") or []):
        if not row.get("is_finished_item"):
            continue
        qty = flt(row.get("qty"))
        if qty <= 0:
            continue
        planned = frappe.db.sql(
            """SELECT qty_to_manufacture, custom_total_produced
               FROM `tabDetox Production Plan FG`
               WHERE parent = %s AND parenttype = 'Production Plan'
                 AND item_code = %s
               LIMIT 1""",
            (plan, row.item_code), as_dict=True,
        )
        if not planned:
            continue
        plan_qty = flt(planned[0].qty_to_manufacture)
        produced = flt(planned[0].custom_total_produced)
        if (produced + qty) > plan_qty:
            frappe.msgprint(
                _("This entry exceeds the planned quantity for {0} "
                  "({1}/{2}).").format(
                    row.item_code, produced + qty, plan_qty,
                ),
                title=_("Over-production"),
                indicator="orange",
            )


# --------------------------------------------------------------------------
# total_produced rollup — L07 (kept in Phase 3 alongside the related
# validations; called from Stock Entry on_submit / on_cancel).
# --------------------------------------------------------------------------
def rollup_total_produced_on_submit(doc, method=None):
    purpose = (doc.get("stock_entry_type") or "").strip()
    if purpose not in MFG_TYPES or not doc.get("production_plan"):
        return
    _adjust_total_produced(doc, sign=+1)


def rollup_total_produced_on_cancel(doc, method=None):
    purpose = (doc.get("stock_entry_type") or "").strip()
    if purpose not in MFG_TYPES or not doc.get("production_plan"):
        return
    _adjust_total_produced(doc, sign=-1)


def _adjust_total_produced(doc, sign: int) -> None:
    plan = doc.get("production_plan")
    for row in (doc.get("items") or []):
        if not row.get("is_finished_item"):
            continue
        qty = flt(row.get("qty"))
        if qty <= 0:
            continue
        # Update Table 1 row matching this FG item.
        frappe.db.sql(
            """UPDATE `tabDetox Production Plan FG`
               SET custom_total_produced = COALESCE(custom_total_produced, 0) + %s
               WHERE parent = %s AND parenttype = 'Production Plan'
                 AND item_code = %s""",
            (sign * qty, plan, row.item_code),
        )
